logical/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

	url(r'^cnv$',cn_view, name='cnv'),

	url(r'^yvd/(?P<a>\d+)$',yv_view, name='yvd'),
	url(r'^$',index_view, name='index_home'),
	url(r'^omp3$',mp3_get_query, name='index_g'),
	url(r'^omp3/search-results$',mp3_show_results, name='index_s'),
	url(r'^load/(?P<v_id>[-\w]+)/(?P<d_audio>\d+)$',load_view, name='load'),

	url(r'^load-status$',load_state, name='load-status'),
	url(r'^get-link$',get_file_link, name='get-link'),
	url(r'^on-play/(?P<v_id>[-\w]+)$',on_play, name='on-play'),

	url(r'^log-search-result$',log_search_result_view, name='lsr'),

	
]

vys/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('logical.urls')),
    url(r'^visitor/', include('opinions.urls')),


]

logical/models.py
import json
from django.core.serializers.json import DjangoJSONEncoder

from django.db import models
from collections import OrderedDict
# Create your models here.

from django.conf import settings

#from settings file get value of SHORTCODE_MAX and if is not present then return 15
SHORTCODE_MAX=getattr(settings,"SHORTCODE_MAX",15)


class Uploadmp4(models.Model):
    code=models.CharField(max_length=SHORTCODE_MAX,unique=True,blank=True)

    up = models.FileField(upload_to='videouploads/')
    # uploaded_at = models.DateTimeField(auto_now_add=True)
   

class TemporaryDetails(models.Model):
	title=models.CharField(max_length=250,blank=False)
	v_id=models.CharField(max_length=250,blank=False)
	d_audio=models.IntegerField(blank=False)



class JSONField(models.TextField):
    """
    JSONField is a generic textfield that neatly serializes/unserializes
    JSON objects seamlessly.
    Django snippet #1478

    example:
        class Page(models.Model):
            data = JSONField(blank=True, null=True)


        page = Page.objects.get(pk=5)
        page.data = {'title': 'test', 'type': 3}
        page.save()
    """

    def to_python(self, value):
        if value == "":
            return None

        try:
            if isinstance(value, str):
                return json.loads(value)
        except ValueError:
            pass
        return value

    def from_db_value(self, value, *args):
        return self.to_python(value)

    def get_db_prep_save(self, value, *args, **kwargs):
        if value == "":
            return None
        if isinstance(value, list):
            value = json.dumps(value, cls=DjangoJSONEncoder)
        return value




class Search_Result(models.Model):
	kw=models.CharField(max_length=250,blank=True)
	sres=JSONField(blank=True, null=True)


'''
JSONField
OrderedDict

https://stackoverflow.com/questions/9686409/how-to-store-a-dictionary-in-a-django-database-models-field

https://stackoverflow.com/questions/5629023/key-order-in-python-dictionaries

https://stackoverflow.com/questions/10844064/items-in-json-object-are-out-of-order-using-json-dumps

'''

logical/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .validators import *
from .models import Uploadmp4

class search_submit_form(forms.Form):
    keyword= forms.CharField(label='', min_length=3, max_length=150)
    
class utube_submit(forms.Form):
    link= forms.CharField(label='', min_length=3, max_length=150,validators=[validate_url])




class Uploadmp4Form(forms.ModelForm):
    class Meta:
        model = Uploadmp4
        exclude = ("code",)

logical/views.py
from django.shortcuts import render
from .forms import *
from .search import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse,HttpResponseRedirect
from .download import *
from urllib.parse import urlparse, parse_qs
import moviepy.editor as mp
import re
from .utils import code_generator,create_shortcode
import os
from django.conf import settings
PATH=settings.STATIC_ROOT
import json
from logical.tasks import load_item,load_search,wait_for_thread
from celery import uuid
from celery.result import AsyncResult
from .models import TemporaryDetails,Search_Result
from collections import OrderedDict

import threading
from django.views.decorators.csrf import csrf_exempt
def index_view(request):
	context={}
	return render(request, 'logical/index.html',context)

# t=threading.Thread()
# ty=threading.Thread()


# Create your views here.
def mp3_get_query(request):
	kw=""
	error_msg=""
	task_id=""
	if request.is_ajax() and request.method=='POST':

		resp={}
		f=search_submit_form(request.POST)
		if f.is_valid():
			kw=f.cleaned_data.get('keyword')
		if kw=="":
			error_msg=f.errors.get('keyword')
			f.errors['keyword']=""
			resp['data']=False
		else:
		
			task_id = uuid()
			ret=load_search.apply_async((str(kw),),task_id=task_id,queue='vys')
			resp['data']=True
		resp['kw']=kw
		resp['tid']=task_id
		resp['emsg']=error_msg
		return HttpResponse(json.dumps(resp), content_type ='application/json; charset=utf8')

	else:
		f=search_submit_form()
	context={
		"form":f,
		"error_msg":error_msg,
		}

	return render(request, 'logical/sdownload.html',context)


@csrf_exempt
def log_search_result_view(request):
	skey=""
	if request.is_ajax() and 'skey' in request.POST.keys():
		skey=request.POST['skey']
		obj=Search_Result.objects.filter(kw=str(skey)).first()
		res_list=obj.sres
		request.session['results']=res_list
		tempd={}
		tempd['all']="_"
		for i in res_list:
			tempd[i['v_id']]=i['title']

		request.session['tempd']=tempd
		

		#obj.delete()
		data=True

	else:
		# 'This is not an ajax request or invalid data'
		data=False
	
	return HttpResponse(json.dumps(data), content_type ='application/json; charset=utf8')





def mp3_show_results(request):

	res_list=[]
	res=[]
	
	if 'results' in request.session.keys():
		res_list=request.session['results']
	
	paginator = Paginator(res_list, 8) 

	page =request.GET.get('page')

	try:
		res = paginator.page(page)

	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		res = paginator.page(paginator.num_pages)
	except:
		# If page is not an integer, deliver first page.
		res = paginator.page(1)


	context={
		"res":res,
	}

	return render(request, 'logical/show_res.html',context)




def uconvert(title):
	res=""
	for i in title:
		if ord(i) in range(ord('A'),ord('Z')+1) or ord(i) in range(ord('a'),ord('z')+1):
			res=res+i
		else:
			res=res+'_'
	return res


@csrf_exempt
def get_file_link(request):
	if request.is_ajax() and'v_id' and 'd_audio' and 'iyview' in request.POST.keys():
		v_id=request.POST['v_id']
		d_audio=request.POST['d_audio']
		iyview=request.POST['iyview']
		
		if str(v_id) is not 'all' and int(d_audio)  in (0,1) and int(iyview)  in (0,1) :
			mm=""
			if int(iyview):
				obj=TemporaryDetails.objects.filter(v_id=str(v_id),d_audio=int(d_audio)).first()
				if obj is not None:
					mm=obj.title
					obj.delete()
			else:

				if 'tempd' in request.session.keys():
					tempd=request.session['tempd']
					mm=uconvert(tempd[v_id])
			
			print('got ' ,v_id)
			print(d_audio)

			vname=""
			aname=""


			if int(d_audio):
				cmd="cd {path}/logical/d_audios; ls {file}.*".format(path=PATH,file=mm)
				mm=os.popen(cmd).read()[:-1]

				aname='logical/d_audios/{s}'.format(s=mm)
				request.session[v_id]={'d_audio':d_audio,'fpath':settings.STATIC_URL+aname}
			else:
				cmd="cd {path}/logical/d_videos; ls {file}.*".format(path=PATH,file=mm)
				mm=os.popen(cmd).read()[:-1]
				vname='logical/d_videos/{s}'.format(s=mm)

				request.session[v_id]={'d_audio':d_audio,'fpath':settings.STATIC_URL+vname}

			data={'aname':settings.STATIC_URL+aname,'vname':settings.STATIC_URL+vname}

		else:
			data = 'Post entries not correct'
	else:
		data = 'This is not an ajax request'
	return HttpResponse(json.dumps(data), content_type ='application/json; charset=utf8')






@csrf_exempt
def load_state(request):
	
	if request.is_ajax():
		# if t in threading.enumerate():
		# 	t.join()
		# 	data=True
		# elif ty in threading.enumerate():
		# 	ty.join()
		# 	data=True
		# else:

		if 'task_id' in request.POST.keys() and request.POST['task_id']:
			task_id = request.POST['task_id']

			data = AsyncResult(task_id).successful()
			print(data)
			# data = AsyncResult(task_id).successful()


			#data = task.result or task.state


	else:
		data = 'This is not an ajax request'
	return HttpResponse(json.dumps(data), content_type ='application/json; charset=utf8')





def load_view(request,v_id=None,d_audio=None):
	if str(v_id) is not 'all' and int(d_audio) is not 8 :

		if 'tempd' in request.session.keys():
			tempd=request.session['tempd']
			ret=False
			task_id = uuid()
			if not d_audio:
				ret=load_item.apply_async((str(v_id),int(d_audio),tempd),task_id=task_id,queue='vys')
				print(task_id)
			else:

				t=threading.Thread(target=dload,args=(str(v_id),int(d_audio),tempd))
				t.start()
				t.join()
				wait_for_thread.apply_async((),task_id=task_id,queue='vys')
				#ret=load_item.delay(str(v_id),int(d_audio),tempd)

	context={'task_id':str(task_id),'v_id':v_id,'d_audio':d_audio,'iyview':0}
	return render(request, 'logical/loading.html',context)






def get_id(url):
    u_pars = urlparse(url)
    quer_v = parse_qs(u_pars.query).get('v')
    if quer_v:
        return quer_v[0]
    pth = u_pars.path.split('/')
    if pth:
        return pth[-1]






				# if int(a):
				# 	cmd="cd {path}logical/d_audios; ls {file}.*".format(path=PATH,file=mm)
				# 	mm=os.popen(cmd).read()[:-1]
				# 	aname='logical/d_audios/{s}'.format(s=mm)
				# else:
				# 	cmd="cd {path}logical/d_videos; ls {file}.*".format(path=PATH,file=mm)
				# 	mm=os.popen(cmd).read()[:-1]
				# 	vname='logical/d_videos/{s}'.format(s=mm)





def yv_view(request,a=None):
	error_msg=""
	lnk=""
	if request.method=='POST':

		f=utube_submit(request.POST)
		if f.is_valid():
			lnk=f.cleaned_data.get('link')
		if lnk=="":
			error_msg=f.errors.get('link')
			f.errors['link']=""
		else:
			vid=get_id(lnk)
			if vid is not None:
				
				mapy={}

				ret=False
				task_id = uuid()

				if not int(a):
					ret=load_item.apply_async((str(vid),int(a),mapy),task_id=task_id,queue='vys')
					print(task_id)
				else:
			
					ty=threading.Thread(target=dload,args=(str(vid),int(a),mapy))
					ty.start()
					ty.join()
					wait_for_thread.apply_async((),task_id=task_id,queue='vys')

				context={'task_id':str(task_id),'v_id':str(vid),'d_audio':int(a),'iyview':1}
				return render(request, 'logical/loading.html',context)


	else:
		f=utube_submit()
	
	context={
		"form":f,
		"error_msg":error_msg,

		"ia":int(a)
		}


	return render(request, 'logical/yvdownload.html',context)



def on_play(request,v_id=None):
	is_audio=1
	fpath=""
	name=""
	if v_id in request.session or v_id=="cnv":
		if v_id=="cnv":
			data=request.session["cnv"]
		else:
			data=request.session[v_id]
		is_audio=int(data['d_audio'])
		fpath=data['fpath']
		name=os.path.basename(fpath)
		del request.session[v_id]
	context={
		"is_audio":is_audio,
		"fpath":fpath,
		'name':name
		}

	return render(request, 'logical/online_play.html',context)

	

# def yv_view(request,a=None):
# 	lnk=""
# 	particular=0
# 	error_msg=""
# 	vname=""
# 	aname=""
# 	if request.method=='POST':

# 		f=utube_submit(request.POST)
# 		if f.is_valid():
# 			lnk=f.cleaned_data.get('link')
# 		if lnk=="":
# 			error_msg=f.errors.get('link')
# 			f.errors['link']=""
# 		else:
# 			vid=get_id(lnk)
# 			if vid is not None:
# 				mm=""
# 				mapy={}

# 				mm=dload(str(vid),int(a),mapy)
# 				particular=1
# 				if int(a):
# 					cmd="cd {path}logical/d_audios; ls {file}.*".format(path=PATH,file=mm)
# 					mm=os.popen(cmd).read()[:-1]
# 					aname='logical/d_audios/{s}'.format(s=mm)
# 				else:
# 					cmd="cd {path}logical/d_videos; ls {file}.*".format(path=PATH,file=mm)
# 					mm=os.popen(cmd).read()[:-1]
# 					vname='logical/d_videos/{s}'.format(s=mm)




# 	else:
# 		f=utube_submit()
# 	context={
# 		"form":f,
# 		"error_msg":error_msg,
# 		"particular":particular,
# 		"vname":vname,
# 		"aname":aname,
# 		"ia":int(a)
# 		}


# 	return render(request, 'logical/yvdownload.html',context)



def repspace(fname):

	fname=fname.replace(" ","_")
	return str(fname)

def get_extension(name):
	return re.findall(r'.\w+$',name)[0][:]




def cn_view(request):

	if request.method == 'POST':
		got_up=''

		if 'up' in request.FILES:
			got_up=request.FILES['up'].name

		ext=get_extension(str(got_up))
		code=create_shortcode()

		request.FILES['up'].name=str(code+ext)

		form = Uploadmp4Form(request.POST, request.FILES)

		if form.is_valid():
			form=form.save(commit=False)
			form.code=code
			form.save()

			fname=repspace(str(got_up))
			clip = mp.VideoFileClip("media/videouploads/"+str(code+ext))
			lname=fname.replace(ext,str(code+'.mp3'))
			fname="static/logical/d_audios/"+lname
			clip.audio.write_audiofile(fname)
			cmd='cd media/videouploads; rm {s}'.format(s=str(code+ext))
			os.system(cmd)
			instance=Uploadmp4.objects.filter(code=code)
			instance.delete()
			aname='logical/d_audios/'+lname
			context={
				"res":0,
				"particular":1,
				"aname":aname,
				"vname":'',
				"daudio":int(1)
				}
			res={}
			res['data']= " {s} ".format(s=settings.STATIC_URL+aname)
			request.session["cnv"]={'d_audio':1,'fpath':res['data']}
			return HttpResponse(json.dumps(res))
			# return render(request, 'logical/sdownload.html',context)

	else:
		form = Uploadmp4Form()


	context={'form': form}

logical/templates/logical/convertmp43.html
{% extends 'base.html' %}
{% load static %}

{% block content %}



  <section id="home">

   	<div class="overlay"></div>

   	<div class="home-content-table" style="   background: linear-gradient(to right, #20002c, #cbb4d4);">
   	
		   <div class="home-content-tablecell">
			  				<h1 class="animate-intro">opiMiner::converter</h1>
				  			<br>
				  			<br>
				  			<h3 class="animate-intro">
							Convert mp4 to mp3<br>
							without affecting the quality
				  			</h3>	


       
       

<!-- 
<div class='row'>
	<div class='col-twelve'>
<input type="text" class="form-control" name="link" required="" id="id_link" minlength="3" maxlength="150" placeholder="Paste video url..." style="  display: block;  margin: 0;  box-shadow: 0 0 1px 1px #969696;   font-family: sans-serif; font-color:white;   appearance: none;    color:red;  border: solid  #969696; height: 100% ">

   	       </div>

<div class='col-twelve'>

      <input class="btn btn-secondary" style="display: block;  margin: 0 auto; cursor:pointer ; background-color: rgba(0,0,0,0.1); color:white;  box-shadow: 0 0 5px 2px #969696; height: 100%"  name="submit" type="submit" value="Download">
</div>
    </div>
 -->

 <div class='row' id="status" hidden>


<div class='col-lg-12 col-sm-12 col-md-12' style='color:yellow'><p id="text-para"></p></div>

<div class="progress " style="height: 30px; width:100%">
  <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="height: 100%; width: 0%"></div>
</div>
</div>


<blockquote hidden id="cnv_status" style="color:yellow;"><b ><p style="font-size:40px"> Converting</p></b>
  <i class="fa fa-spinner fa-spin" style="font-size:100px"></i> 
</blockquote>


 <div class='row' id="output" hidden>


<div class='col-lg-12 col-sm-12 col-md-12'><b style="color:#F0FFF0; font-size:30px; font-family:'Comic Sans' cursive; "> Here's your mp3</b> <i class="fa fa-music fa-stack-2x" style='color:orange; opacity:0.2 ; font-size: 60px' aria-hidden="true"></i> </div>

<div class='col-lg-6 col-sm-6 col-md-6' style="padding-top: 2%; "><a id='play' target='_blank' href='{% url "on-play" "cnv" %}' style="color:yellow; float:center" class= " btn btn-outline-danger btn-lg"><b> Play Online </b><i class="fa fa-play-circle "  style='color:yellow; opacity:0.5 ; ' 	aria-hidden="true"></i> </a></div>

<div class='col-lg-6 col-sm-6 col-md-6' style="padding-top: 2%"><a id='dload' download href='#'  style="color:yellow; float:center" class= " btn btn-outline-danger btn-lg" ><b> Download </b><i class="fa fa-download "  style='color:yellow; opacity:0.5 ;' aria-hidden="true"></i></a></div>


</div>


 <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   
    <div class='row' id='file-div'>
<!-- 	<div class='col-lg-4 col-sm-0 col-md-4'>
    </div> -->
	<div  class='col-lg-12 col-sm-12 col-md-12'>

    <input type="file" name="up" required="" id="id_up" style="  display: block;  margin: 0;cursor:pointer ;  box-shadow: 0 0 5px 5px black; width: 100%; height: 100%;   font-family: sans-serif; font-color:white;   appearance: none;    color:yellow;  border: solid  black  ">

</div>



<!-- <div class='col-lg-4 col-sm-0 col-md-4'>
    </div>
 

<div class='col-lg-12 col-sm-0 col-md-12' >
    
    <input hidden class="btn btn-secondary" style="display: block;  margin: 0 auto; cursor:pointer ; background-color: rgba(0,0,0,0.1); color:white;   box-shadow: 0 0 2px 5px #969696;  margin-top: 3%; "  name="submit" type="submit" value="Convert">
</div>
-->
</div>
 
  </form>

<!-- <input type="button" value="click me" onclick="doing_fun()">

<p id="doing"></p>

 -->
 

 
		   </div> <!-- end home-content-tablecell --> 		   
		</div> <!-- end home-content-table -->


   </section> <!-- end home -->




{% endblock %}

{% block include_scripts %}



<script src="{% static 'logical/js/uploadjs/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'logical/js/uploadjs/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'logical/js/uploadjs/jquery.fileupload.js' %}"></script>

<script>
$(function () {
    $('#id_up').fileupload({
        
        dataType: 'json',
        
        add: function (e, data) {


			console.log('began Uploading');
            data.submit();
            $('#status').removeAttr('hidden');
            $( "#file-div" ).replaceWith($('#status'));
       
        },


        done: function (e, data) {
        	file_link=data.result['data']
        	console.log(file_link);
		   	$('#dload').attr('href',file_link);
		   	
		   	$('#output').removeAttr('hidden');
     
        	$('#cnv_status').attr('hidden');
            $( "#cnv_status" ).replaceWith($('#output'));



         /*   $.each(data.result.files, function (index, file) {
                $('<p/>').text(file.name).appendTo(document.body);
                console.log(file.name);
            });
*/
        },

         progressall: function (e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        $('.progress .progress-bar').css(
            'width',
            progress + '%'
        );
        $('#text-para').html('Uploading : <b>'+ progress + '%</b>');
        if(progress==100)
    	{
           	$('#cnv_status').removeAttr('hidden');
     
        	$('#status').attr('hidden');
            $( "#status" ).replaceWith($('#cnv_status'));
        }
    }

    });

 

});


</script>




<!-- <script type="text/javascript">
	function doing_fun()
	{

		document.getElementById("doing").innerHTML = "Uploading and Converting..";
	}
</script>
 -->
{% endblock %}

logical/templates/logical/online_play.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

   <section id="home">

   	<div  class="overlay"></div>

   	<div  class="home-content-table" style="
	      background: linear-gradient(to right, #20002c, #cbb4d4);">
   			
		   <div class="home-content-tablecell">
		   	<div   class="row">
		   		<div class="col-twelve">		   			
		   		<h4 class="animate-intro">
		   			{{name}}
		   		</h4>	
		   		{% if is_audio %}
				   	<audio controls>
			  			<source src="{{fpath}}" type="audio/mp3">
					  <source src="{{fpath}}" type="audio/ogg">
					</audio>
		   		{% else%}

				<video poster="" controls>
				  <source src="{{fpath}}" type="video/mp4">
				  <source src="{{fpath}}" type="video/webm">
				  <!-- Captions are optional -->
				  <track kind="captions" label="English captions" src="" srclang="en" default>
				</video>
		   		{% endif %}		



			  		</div> 
             </div>
       
       

				  			<div class="more animate-intro">
				  			

				  			<!-- 	<a class="smoothscroll button stroke" href="#">
				  					
				  				</a> -->
				  			</div>							
 
		   </div> <!-- end home-content-tablecell --> 		   
		</div> <!-- end home-content-table -->


   </section> <!-- end home -->








{% endblock %}

{% block include_scripts %}


{% endblock %}

logical/templates/logical/sdownload.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

   <section id="home">

   	<div class="overlay"></div>

   	<div class="home-content-table" style="   background: linear-gradient(to right, #20002c, #cbb4d4); ">
   	
		   <div class="home-content-tablecell">
		   	<div class="row">
		   		<div class="col-twelve">		   			
			  		
			  				
			  				<h1 class="animate-intro">opiMiner::gomp3</h1>

<div id="prep" class='row' hidden >

<blockquote  class='col-lg-12 col-sm-12 col-md-12' style='color:white'><p style="font-size:30px">Fetching Search Results</p>  <i class="fa fa-search fa-spin" style="font-size:80pt"> </i></blockquote>

</div>


				  			<div id='qsub'>
				  			<br>
				  			<br>
				  			<h3 class="animate-intro">
							Free and Fast download <br>
							any mp3 or video song..
				  			</h3>	

			   <form id='search_form' method='POST' action='./omp3'>{% csrf_token %}


    <div class="input-group row" >

	<div  class='col-lg-12 col-sm-12 col-md-12'>

   	<input type="text" class="form-control" name="keyword" id="id_keyword" required="" maxlength="150" minlength="3" placeholder="Search song..." style="  display: block;  margin: 0;  box-shadow: 0 0 3px 4px black;   font-family: sans-serif; font-color:white;   appearance: none;    color:red;  border: solid  black; height: 100%;width: 100% 	">
</div>
	<div  class='col-lg-12 col-sm-12 col-md-12'>

        <input class="btn btn-outline-danger" style="display: block; margin: 0 auto; cursor:pointer ;  color:black;  box-shadow: 0 0 1px 2px black; height: 100%"  name="submit" type="submit" value="Go!">
</div>
    </div>
    </form>

  
 

			  		</div> 
			  	</div>
             </div>
       
       

				  			<div class="more animate-intro">
				  			

				  			<!-- 	<a class="smoothscroll button stroke" href="#">
				  					
				  				</a> -->
				  			</div>							
 
		   </div> <!-- end home-content-tablecell --> 		   
		</div> <!-- end home-content-table -->


		<!-- <ul class="home-social-list">
	      <li class="animate-intro">
	        	<a href="#"><i class="fa fa-facebook-square"></i></a>
	      </li>
	      <li class="animate-intro">
	        	<a href="#"><i class="fa fa-twitter"></i></a>
	      </li>
	      <li class="animate-intro">
	        	<a href="#"><i class="fa fa-instagram"></i></a>
	      </li>
         <li class="animate-intro">
           	<a href="#"><i class="fa fa-behance"></i></a>
         </li>
	      <li class="animate-intro">
	        	<a href="#"><i class="fa fa-dribbble"></i></a>
	      </li>	      
	   </ul> 
		<div class="scrolldown">
			<a href="#about" class="scroll-icon smoothscroll">		
		   	Scroll Down		   	
		   	<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
			</a>
		</div>			
    -->

   </section> <!-- end home -->


{% endblock %}

{% block include_scripts %}

<script type="text/javascript">

function load_the_search(tid,kw)
{

var poll_xhr;
var willstop = 0;
(function(){
var poll = function(){

var task_id=tid;
var skey=kw;

console.log(task_id)
poll_xhr = $.ajax({
	type: "POST",
	url: "{% url 'load-status' %}",
  	dataType: 'json', // added data type
	data: {
	task_id: task_id,
	},

	success: function(result) {
	if (result)
	{
		willstop=1;

		$.ajax({
				
				type: "POST",
				url: "{% url 'lsr' %}",
			  	dataType: 'json', // added data type
				data: {
					skey: skey,
				},

				success: function(flag) 
				{
					if(flag)
					{
						window.location.replace("{% url 'index_s' %}");

					}
					else
					{
						console.log("Encountered some error");
					}
					console.log(flag);

				},
		});
	}
	else
	{
		console.log(result);
			
	}

}
});
};
 
var refreshIntervalId = setInterval(function() {
poll();
if(willstop == 1){
clearInterval(refreshIntervalId);
}
},500);
})();


}














$('#search_form').on('submit', function(event){
    event.preventDefault();
//    console.log("form submitted!")  // sanity check
    submit_keyword();
});


function submit_keyword() {
    var form_data=$('#search_form').serializeArray();
    $.ajax({
        url : "./omp3", // the endpoint
        content_type: 'application/json; charset=utf-8',
        type : "POST", // http method
        data : form_data, // data sent with the post request

        // handle a successful response
        success : function(server_response) {
        	if (server_response['data'])
        	{
            	console.log('query submitted');
            	
            	
            	
            	$('#search_form').each(function(){
 			   			this.reset();
 			   	});

            		$('#prep').removeAttr('hidden');
					$('#qsub').attr('hidden');
					$( "#qsub" ).replaceWith($('#prep'));

 			   		
 			   		load_the_search(server_response['tid'],server_response['kw']);

         
            }
            else
            {
            	console.log("error in validating form"); // another sanity check

				alert(server_response['emsg']);

            }
        },

        // handle a non-successful response
        error : function(server_response) {
        		console.log('ajax request unsuccessful');

        }
    });
};

</script>



{% endblock %}